version: '3'

services:
  traefik:
    image: traefik:v2.2
    container_name: traefik
    hostname: traefik
    restart: always
    env_file:
      - traefik.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.toml:/traefik.toml
      - ./config/dyn.toml:/dyn.toml
      - ./tls/acme.json:/acme.json
      - ./auth/usersFile:/usersFile
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - web
    labels:
      - "traefik.http.routers.traefik.rule=Host(`traefik.vendoor.me`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=le"
      - "traefik.http.middlewares.traefikAuth.basicauth.usersfile=/usersFile"
      - "traefik.http.routers.traefik.middlewares=traefikAuth@docker"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:[a-z-.]+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=http"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  landing:
    image: docker.pkg.github.com/vendoor/vendoor-landing/vendoor-landing:production-latest
    hostname: landing
    container_name: landing
    restart: always
    ports:
      - "80"
    networks:
      - web
    labels:
      - "traefik.http.routers.landing.rule=HOST(`vendoor.me`) && PathPrefix(`/`)"
      - "traefik.http.routers.landing.tls=true"
      - "traefik.http.routers.landing.tls.certresolver=le"
      - "traefik.http.routers.landing.entrypoints=https"

  client:
    image: docker.pkg.github.com/vendoor/vendoor-client/vendoor-client:production-latest
    hostname: client
    container_name: client
    restart: always
    ports:
      - "80"
    networks:
      - web
    labels:
      - "traefik.http.routers.client.rule=HOST(`app.vendoor.me`) && PathPrefix(`/`)"
      - "traefik.http.routers.client.tls=true"
      - "traefik.http.routers.client.tls.certresolver=le"
      - "traefik.http.routers.client.entrypoints=https"

  server:
    image: docker.pkg.github.com/vendoor/vendoor-server/vendoor-server:production-latest
    hostname: server
    container_name: server
    restart: always
    env_file:
      - server.env
    ports:
      - "3000"
    networks:
      - web
    labels:
      - "traefik.http.routers.client.rule=HOST(`app.vendoor.me`) && PathPrefix(`/api`)"
      - "traefik.http.routers.client.tls=true"
      - "traefik.http.routers.client.tls.certresolver=le"
      - "traefik.http.routers.client.entrypoints=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"

networks:
  web:
    external: true
