[log]
  level = "ERROR"

[entryPoints]
  [entryPoints.http]
    address = ":80"

  [entryPoints.https]
    address = ":443"
    [entryPoints.https.http.tls]

[api]
  dashboard = true

[providers]
  [providers.docker]

[certificatesResolvers.le.acme]
  email = "lajoskvcs@icloud.com"
  storage = "/acme.json"
  [certificatesResolvers.le.acme.dnsChallenge]
    provider = "digitalocean"
    delayBeforeCheck = 0
